// GIVEN a command-line application that accepts user input
// WHEN I am prompted for my team members and their information
// THEN an HTML file is generated that displays a nicely formatted team roster based on user input
// WHEN I click on an email address in the HTML
// THEN my default email program opens and populates the TO field of the email with the address
// WHEN I click on the GitHub username
// THEN that GitHub profile opens in a new tab
// WHEN I start the application
// THEN I am prompted to enter the team manager’s name, employee ID, email address, and office number
// WHEN I enter the team manager’s name, employee ID, email address, and office number
// THEN I am presented with a menu with the option to add an engineer or an intern or to finish building my team
// WHEN I select the engineer option
// THEN I am prompted to enter the engineer’s name, ID, email, and GitHub username, and I am taken back to the menu
// WHEN I select the intern option
// THEN I am prompted to enter the intern’s name, ID, email, and school, and I am taken back to the menu
// WHEN I decide to finish building my team
// THEN I exit the application, and the HTML is generated
// 
// 
// create employee parent class
    // refer to readme
    // run tests to make them pass

// create manager class extending employee class
    // refer to readme for needed
    // run tests to make them pass

// create engineer class extending employee class
    // refer to readme
    // run tests and make pass

// create intern class extending employee class
    // refer to readme
    // run tests and make pass

// 
// Inquirer question asking what type of employee with selection
// depending on selection - navigate to inquirer question set that covers Employee class and additional subclass requirements
    // Question set for Employee
    // question set for manager
    // question set for Engineer
    // question set for intern
// Inquirer question asking if done or selecting another employee 
// take information from Inquirer questions and put into generateTeam const in generateHtml.js
// import team to index.js
// put team from generateHtml.js into write file function where pushes file to OUTPUT folder in directory
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 